import "./globals.css";
import UserProvider from "./context/UserContext";
import NavBar from "./components/NavBar";

export const metadata = {
  title: "GOOD HAMBURGER",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <NavBar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
